# These are supported funding model platforms

github: [Akunimal] # Replace with your GitHub username if you enable GitHub Sponsors
# patreon: user-name
# open_collective: project-name
# ko_fi: user-name
# custom: ['https://example.com/donate']
